services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    networks:
      - postgres

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - redis

  web:
    build:
      context: .
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=server.settings.production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
      - POSTGRES_PORT=5432
    ports:
      - 8000:8000
    networks:
      - postgres
      - redis
    depends_on:
      - db
      - redis



volumes:
  postgres_data:

networks:
  redis:
    driver: bridge
  postgres:
    driver: bridge